apiVersion: v1
kind: Namespace
metadata:
   name: $${NAMESPACE}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cs-demo-deployment
  namespace: $${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: codestream-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: codestream-demo
    spec:
      containers:
      - name: codestream-demo
        image: ddeswart/codestream-demo:$${NAMESPACE}-$${JOB_ID}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codestream-demo
  name: codestream-demo-svc
  namespace: $${NAMESPACE}
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: codestream-demo
